# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SDS 201 Labs
email: whopper@smith.edu
author: "Herp"
description: >- # this means to ignore newlines until "baseurl:"
  Lab slides and accompanying files for the SDS 201 labs taught by Will Hopper.

baseurl: "/sds201_labs" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  wjhopper
repository: wjhopper/sds201_labs

# Build settings
markdown: kramdown
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
highlighter: rouge
permalink: none

# jekyll-paginate configuration
paginate: 15

sass:
  sass_dir: assets/css
  style: :nested

defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: /posts/:title

collections:
  labs:
    order:
      - "Intro to R and RStudio"
      - "Data Visualization with ggplot"
      - "Data Types and Manipulation"
      - "Data Manipulation with dplyr"
      - "Reshaping and Exploring Data"
      - "Bivariate Regression"
      - "Multiple Regression"
      - "Sampling Distributions"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - LICENCSE.md
   - renv/
   - renv.lock
   - sds201_labs.Rproj
   - labs_source/
   - R/
