# Change 'comments' to true for Disqus comments
disqus:
  comments: false
#  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Problem Sets', folder: 'pages', file: 'problem-sets.html'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

